# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-04 16:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='company', max_length=255)),
                ('website', models.URLField()),
                ('headquarters', models.CharField(max_length=255)),
                ('industry', models.CharField(max_length=255)),
                ('revenue', models.IntegerField()),
                ('size', models.IntegerField()),
                ('founded', models.DateField()),
                ('summary', models.TextField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Company_Reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('star_rating', models.PositiveSmallIntegerField(default='0')),
                ('title', models.CharField(default='', max_length=300)),
                ('review', models.TextField(default='')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('companykey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='review.Company')),
            ],
        ),
    ]
