# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-30 16:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website', models.URLField()),
                ('headquarters', models.CharField(max_length=255)),
                ('industry', models.CharField(max_length=255)),
                ('revenue', models.IntegerField()),
                ('size', models.IntegerField()),
                ('founded', models.DateField()),
                ('summary', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Company_Reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metarating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('linkedin_icon', models.ImageField(height_field=100, upload_to=b'', width_field=100)),
                ('linkedin_stars', models.DecimalField(decimal_places=2, max_digits=3)),
                ('review_text', models.TextField(max_length=2000)),
                ('companykey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='review.Company')),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='email',
            field=models.EmailField(default='noreply@example.com', max_length=254),
        ),
    ]
