# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 04:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_auto_20170930_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='company_reviews',
            name='company_name',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='company_reviews',
            name='review',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='company_reviews',
            name='star_rating',
            field=models.PositiveSmallIntegerField(default='0'),
        ),
    ]
