# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-21 20:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0003_auto_20171003_0420'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company_reviews',
            name='linkedin_icon',
        ),
        migrations.RemoveField(
            model_name='company_reviews',
            name='linkedin_stars',
        ),
        migrations.RemoveField(
            model_name='company_reviews',
            name='metarating',
        ),
        migrations.RemoveField(
            model_name='company_reviews',
            name='review_text',
        ),
    ]
