# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-21 20:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0004_auto_20171021_2013'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='company_name',
            field=models.CharField(default='company', max_length=255),
        ),
    ]
