# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-22 18:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0005_company_company_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
    ]
