# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-22 21:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('review', '0006_delete_person'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company_reviews',
            old_name='company_name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='company_reviews',
            name='author',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='company_reviews',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='company_reviews',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
